---
- name: Ubuntu - add cloud-archive repo
  command: >-
    apt-add-repository -y cloud-archive:{{ cloud_archive | default('stein') }}

- name: Ubuntu - Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: true
    force_apt_get: true

- name: Ubuntu - Ensure openvswitch is installed
  apt:
    name: openvswitch-switch

- set_fact:
    openvswitch_service: openvswitch-switch
