---
- name: EL7 - Find grub.cfg
  stat:
    path: "{{ item }}"
  with_items:
    - /boot/grub2-efi/grub.cfg
    - /boot/grub2/grub.cfg
    - /etc/grub2.cfg
    - /etc/grub2-efi.cfg
  register: grubcfg

- name: EL7 - Reset grub2 config
  command: grub2-mkconfig -o {{ item.item }}
  with_items: "{{ grubcfg.results }}"
  when: item.stat.exists and not item.stat.islnk

- name: EL7 - Select latest kernel
  shell: >-
    rpm -qa kernel | rpmdev-sort | tail -n 1 |sed 's/^kernel/\/boot\/vmlinuz/'
  args:
    warn: no
  register: latest_kernel

- command: grubby --set-default={{ latest_kernel.stdout | trim }}

- command: >-
    grubby --args="{{ grub_cmdline_args | join(' ') }}" --update-kernel=ALL
