---
# Execute with "ansible-playbook playbook.yaml -i hosts.yaml -v"
- name: Prepare devstack setup
  hosts: all
  become: true
  roles:
  - role: system-logging
    tags: system-logging
  - role: required-packages
    tags: required-packages
  - role: cleanup-cloud-init
    tags: cleanup-cloud-init
  - role: vfio-module
    tags: vfio-module
  - role: flower-firmware
    tags: flower-firmware
  - role: network-config
    tags: network-config
  - role: switchdev
    tags: switchdev
  - role: probe-tuning-profile
    tags: probe-tuning-profile
  - role: kernel-settings
    tags: kernel-settings
  - role: swap
    tags: swap
  - role: devstack
    tags: devstack
  - role: openvswitch
    tags: openvswitch
  - role: virtio-forwarder
    tags: virtio-forwarder
  - role: aovs-plugin
    tags: aovs-plugin
